framework: golang
version: 1.2.0
# blocklist:
#   - "/home/nucleus/repo/api/client/client_test.go##TestBasicCall"
#   - "/home/nucleus/repo/cache/memory_test.go##TestCache"
preRun:
  command:
    - "go get -v -t -d ./..."
    - "go mod vendor"

postMerge:
  pattern:
    - ""
    #test
